// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1KBfyThFEy54Yqxbv5n_esKFhJ1ZlH34',
    appId: '1:687002127543:web:9c65016c812576ffad9132',
    messagingSenderId: '687002127543',
    projectId: 'auth1-6cbbe',
    authDomain: 'auth1-6cbbe.firebaseapp.com',
    storageBucket: 'auth1-6cbbe.firebasestorage.app',
    measurementId: 'G-TW64D81RY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm3S2MHLPIE6X5_f4g1rYloTS6ZDADC-0',
    appId: '1:687002127543:android:21955d61daa08194ad9132',
    messagingSenderId: '687002127543',
    projectId: 'auth1-6cbbe',
    storageBucket: 'auth1-6cbbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgxGBov0u1_F4szXKXtsrguajHC-TanfQ',
    appId: '1:687002127543:ios:a7e7d7fbd2ce6d19ad9132',
    messagingSenderId: '687002127543',
    projectId: 'auth1-6cbbe',
    storageBucket: 'auth1-6cbbe.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgxGBov0u1_F4szXKXtsrguajHC-TanfQ',
    appId: '1:687002127543:ios:a7e7d7fbd2ce6d19ad9132',
    messagingSenderId: '687002127543',
    projectId: 'auth1-6cbbe',
    storageBucket: 'auth1-6cbbe.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1KBfyThFEy54Yqxbv5n_esKFhJ1ZlH34',
    appId: '1:687002127543:web:eef5893cab59c865ad9132',
    messagingSenderId: '687002127543',
    projectId: 'auth1-6cbbe',
    authDomain: 'auth1-6cbbe.firebaseapp.com',
    storageBucket: 'auth1-6cbbe.firebasestorage.app',
    measurementId: 'G-B0JKMYN0MK',
  );
}
